version: '3.4'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: catalogdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - catalogdbdata:/var/opt/mssql
    restart: always
